default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  encoding: utf8
  database: test_guru_development
  username: dekan
  password: 

test:
  <<: *default
  encoding: utf8
  database: test_guru_test
  username: dekan
  password: 

production:
  <<: *default
  encoding: unicode
  database: test_guru_production
